---
- name: Create group
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ teuthology_users }}"
  tags:
    - user

- name: Create users
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
  with_items: "{{ teuthology_users }}"
  tags:
    - user

# test-admins group gets sudo rights to /bin/kill pids (used by teuthology-kill)
- name: Create test-admins group
  group:
    name: test-admins
    state: present
  tags:
    - user

- name: Add test_admins to test-admins group
  user:
    name: "{{ item }}"
    groups: test-admins
    append: yes
  with_items: "{{ test_admins }}"
  tags:
    - user
  when: test_admins is defined and test_admins|length > 0

- name: Grant test-admins sudo access to /bin/kill
  lineinfile:
    dest: /etc/sudoers.d/cephlab_sudo
    regexp: "^%test-admins"
    line: "%test-admins ALL=NOPASSWD: /bin/kill, /usr/bin/kill"
    state: present
    validate: visudo -cf %s
  tags:
    - user

- name: Determine teuthology GitHub PR
  set_fact:
    teuthology_ghpr: "{{ teuthology_branch | regex_replace( '^origin/pr/([^\/]+)/.*$', '\\1') }}"

- name: Clone the teuthology repo for GitHub PR
  git:
    repo: "https://github.com/ceph/teuthology"
    dest: /home/{{ item }}/src/teuthology_master
    version: "{{ teuthology_branch }}"
    refspec: '+refs/pull/{{ teuthology_ghpr }}/*:refs/origin/pr/{{ teuthology_ghpr }}/*'
  become_user: "{{ item }}"
  with_items: "{{ teuthology_users }}"
  tags:
    - repos
  when: teuthology_ghpr is defined and teuthology_ghpr != teuthology_branch

- name: Clone the teuthology repo
  git:
    repo: "{{ teuthology_repo }}"
    dest: /home/{{ item }}/src/teuthology_master
    version: "{{ teuthology_branch }}"
  become_user: "{{ item }}"
  with_items: "{{ teuthology_users }}"
  tags:
    - repos
  when: teuthology_ghpr is not defined or teuthology_ghpr == teuthology_branch

- name: Run bootstrap
  shell: NO_CLOBBER=true ./bootstrap
  args:
    chdir: /home/{{ item }}/src/teuthology_master/
  become_user: "{{ item }}"
  with_items: "{{ teuthology_users }}"
  register: bootstrap
  changed_when: bootstrap.stdout_lines[-1]|length > 60
  tags:
    - repos
  
- name: Add teuthology scripts to PATH
  lineinfile:
    dest: /home/{{ item }}/.profile
    regexp: teuthology_master
    line: 'PATH="$HOME/src/teuthology_master/virtualenv/bin:$PATH"'
  become_user: "{{ item }}"
  with_items: "{{ teuthology_users }}"

- name: Ensure teuthology is usable
  shell: "./teuthology --version"
  args:
    chdir: /home/{{ item }}/src/teuthology_master/virtualenv/bin/
  become_user: "{{ item }}"
  with_items: "{{ teuthology_users }}"
  changed_when: false

- name: Ensure archive directory exists
  shell: "mkdir -p {{ archive_base }}/worker_logs"
  become_user: "{{ teuthology_execution_user }}"
  tags:
    - logs
