---
timezone: "Etc/UTC"

# Red Hat Subscription Manager credentials
subscription_manager_activationkey: ""
subscription_manager_org: ""

# Repos to enable in Red Hat Subscription Manager
rhsm_repos: []

# Defines whether to use a Red Hat Satellite server
use_satellite: false

kerberos_realm: EXAMPLE.COM

epel_mirror_baseurl: "http://dl.fedoraproject.org/pub/epel"
epel_repos:
  epel:
    name: "Extra Packages for Enterprise Linux"
    metalink: "https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch&infra=$infra&content=$contentdir"
    # ternary requires ansible >= 1.9
    enabled: "{{ enable_epel | ternary(1, 0) }}"
    gpgcheck: 0
  epel-testing:
    name: "Extra Packages for Enterprise Linux - Testing"
    metalink: "https://mirrors.fedoraproject.org/metalink?repo=testing-epel{{ ansible_distribution_major_version }}&arch=$basearch&infra=$infra&content=$contentdir"
    enabled: 0
    gpgcheck: 0

enable_epel: true
yum_timeout: 300

# Override in secrets repo
nagios_allowed_hosts: "127.0.0.1"

# Override in roles/common/vars/os_version.yml
nrpe_selinux_packages:
  - libsemanage-python
  - policycoreutils-python

# Is this a containerized node?
containerized_node: false
