# {{ ansible_managed }}
lock_server: {{ paddles_address }}
results_server: {{ paddles_address }}
results_ui_server: {{ pulpito_address }}
results_email: {{ teuthology_results_email|default('null') }}
results_sending_email: {{ teuthology_results_sending_email|default('null') }}
lab_domain: {{ lab_domain|default('teuthology') }}
default_machine_type: {{ teuthology_default_machine_type|default('null') }}
max_job_time: {{ teuthology_max_job_time|default(129600) }}
{{ teuthology_yaml_extra }}
# Not yet configurable via ansible
archive_server: http://{{ inventory_hostname }}/
archive_base: {{ archive_base }}
ceph_git_base_url: {{ teuthology_ceph_git_base_url }}
queue_host: localhost
queue_port: 11300
# for virtual ips (vip task)
vip:
  - machine_subnet: 172.21.0.0/20
    virtual_subnet: 10.0.0.0/16
