---
- name: Install cobbler
  yum:
    name: "{{ cobbler_package }}"
    state: latest
  register: install_cobbler

- name: Install extra cobbler packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ cobbler_extra_packages }}"
  when: cobbler_extra_packages|length > 0

# configure red hat specific things
- include_tasks: setup-redhat.yml
  when: ansible_distribution in ('RedHat', 'CentOS')
