---
- name: Make sure supervisor config directory exists
  file:
    path: "{{ supervisor_conf_d }}"
    state: directory
    recurse: yes
    mode: 0755

- name: Ship supervisor config
  template:
    src: supervisor.conf
    dest: "{{ supervisor_conf_d }}/paddles.{{ supervisor_conf_suffix }}"
    mode: 0755
  register: supervisor_conf

- name: Read supervisord config
  command: supervisorctl update
  when: supervisor_conf is changed

- name: Ensure paddles is running
  supervisorctl:
    name: paddles
    state: started

- name: Restart paddles if prod.py changed
  supervisorctl:
    name: paddles
    state: restarted
  when: prod_conf is defined and prod_conf is changed
  tags:
    - config

- name: Wait for paddles to start
  wait_for:
    port: "{{ paddles_port }}"
