---
- name: Remove /etc/ceph
  file:
    path: /etc/ceph
    state: absent

- name: Upload weekly kernel-clean crontab.
  template:
    src: cron/kernel-clean
    dest: /etc/cron.weekly/kernel-clean
    owner: root
    group: root
    mode: 0755
  notify:
    - restart cron

# Install and configure cpan and Amazon::S3
- include: cpan.yml
  tags:
    - cpan

- name: Upload /etc/grub.d/02_force_timeout.
  template:
    src: grub.d/02_force_timeout
    dest: /etc/grub.d/02_force_timeout
    owner: root
    group: root
    mode: 0755

- name: Enable kernel logging to console.
  script: scripts/kernel_logging.sh creates=/kernel-logging-setup
  register: kernel_logging
  tags:
    - kernel_logging

- name: Update grub
  command: update-grub
  when: kernel_logging|changed
  tags:
    - kernel_logging

- name: Upload ttyS1.conf.
  template:
    src: ttyS1.conf
    dest: /etc/init/ttyS1.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - start ttyS1

# this only runs on mira nodes
- name: Upload ttyS2.conf.
  template:
    src: ttyS2.conf
    dest: /etc/init/ttyS2.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - start ttyS2
  when: ansible_hostname | search("^mira*")

- name: Enable kernel modules to load at boot time.
  template:
    src: modules
    dest: /etc/modules
    owner: root
    group: root
    mode: 0644

- name: Enabling auto-fsck fix to prevent boot hangup.
  lineinfile:
    dest: /etc/default/rcS
    line: "FSCKFIX=yes"
    regexp: "FSCKFIX=no"
    # backrefs makes it so that if the regexp
    # isn't found the file is left unchanged
    backrefs: yes
    state: present

- include: nfs.yml
  tags:
    - nfs

# this script was ported directly from chef.
- name: Set up static IP and 10gig interface.
  script: scripts/static-ip.sh creates=/static-ip-setup
  when: "'vps' not in group_names"

- name: Upload a lab specific base resolv.conf.
  template:
    src: "{{ item }}"
    dest: /etc/resolvconf/resolv.conf.d/base
    owner: root
    group: root
    mode: 0755
  with_first_found:
    - "resolvconf/base_{{ lab_name }}"
    - resolvconf/base
  notify:
    - restart resolvdns

- name: Edit lvm.conf to support LVM on RBD.
  lineinfile:
    dest: /etc/lvm/lvm.conf
    regexp: "# types ="
    line: 'types = [ "rbd", 1024 ]'
    backrefs: yes
    state: present
