---
packages:
  ## misc tools
  - vim
  - wget
  - mlocate
  - git
  - redhat-lsb-core
  ## bind-specific packages
  - bind
  - bind-utils
  ## firewall
  - firewalld
  ## monitoring
  - nrpe
  - nagios-plugins-all
  ## for NTP
  - ntp
  - ntpdate

bind_service: named
bind_user: named
bind_group: named

named_conf_zones_path: /var/named/zones
