---
packages:
  ## misc tools
  - vim
  - wget
  - mlocate
  - git
  - lsb
  ## bind-specific packages
  - bind
  - bind-utils
  ## firewall
  - firewalld
  ## monitoring
  - nrpe
  - nagios-plugins-all
  ## for NTP
  - ntp
  #- ntpdate
  # do we really need selinux on opensuse?
  - python-selinux

bind_service: named
bind_user: named
bind_group: named

named_conf_zones_path: /var/lib/named
