---
# Restart for config file updates
- name: restart named
  service:
    name: "{{ bind_service }}"
    state: restarted

# Reload for zone file updates
- name: reload named
  service:
    name: "{{ bind_service }}"
    state: reloaded
