---
- name: Install and update packages via yum
  yum:
    name: "{{ packages }}"
    state: latest
    enablerepo: epel
  when: ansible_pkg_mgr == "yum"

- name: Install and update packages via zypper
  zypper:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  when: ansible_pkg_mgr == "zypper"
  tags:
    - packages

- name: Install and update packages via apt
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  when: ansible_pkg_mgr == "apt"
  tags:
    - packages
