---
# These defaults are present to allow certain tasks to no-op if a secrets repo
# hasn't been defined. If you want to override these, do so in the secrets repo
# itself. We override these in  $repo/ansible/inventory/group_vars/nameserver.yml
secrets_repo:
  name: null
  url: null
