---
distros:
  # Distros with empty iso values will be skipped. These dicts will be 
  # updated with same-named items in an 'extra_distros' var, which can be 
  # set in the secrets repo.
  "inktank-rescue":
      iso: ""
  "dban-2.3.0-autonuke":
      iso: ""
  "RHEL-6.6-Server-x86_64":
      iso: ""
  "RHEL-6.7-Server-x86_64":
      iso: ""
  "RHEL-7.0-Server-x86_64":
      iso: ""
  "RHEL-7.1-Server-x86_64":
      iso: ""
  "RHEL-7.2-Server-x86_64":
      iso: ""
  "CentOS-7.0-x86_64":
      iso: http://archive.kernel.org/centos-vault/7.0.1406/isos/x86_64/CentOS-7.0-1406-x86_64-DVD.iso
      sha256: ee505335bcd4943ffc7e6e6e55e5aaa8da09710b6ceecda82a5619342f1d24d9
      kickstart: cephlab_rhel.ks
  "CentOS-7.1-x86_64":
      iso: http://archive.kernel.org/centos-vault/7.1.1503/isos/x86_64/CentOS-7-x86_64-DVD-1503-01.iso
      sha256: 85bcf62462fb678adc0cec159bf8b39ab5515404bc3828c432f743a1b0b30157
      kickstart: cephlab_rhel.ks
  "CentOS-7.2-x86_64":
      iso: http://ftp.linux.ncsu.edu/pub/CentOS/7.2.1511/isos/x86_64/CentOS-7-x86_64-DVD-1511.iso
      sha256: 907e5755f824c5848b9c8efbb484f3cd945e93faa024bad6ba875226f9683b16
      kickstart: cephlab_rhel.ks
  "CentOS-6.7-x86_64":
      iso: http://ftp.linux.ncsu.edu/pub/CentOS/6.7/isos/x86_64/CentOS-6.7-x86_64-bin-DVD1.iso
      sha256: c0c1a05d3d74fb093c6232003da4b22b0680f59d3b2fa2cb7da736bc40b3f2c5
      kickstart: cephlab_rhel.ks
  "Ubuntu-12.04-server-x86_64":
      iso: "http://releases.ubuntu.com/12.04/ubuntu-12.04.5-server-amd64.iso"
      sha256: af224223de99e2a730b67d7785b657f549be0d63221188e105445f75fb8305c9
      kickstart: cephlab_ubuntu.preseed
      kernel_options: "netcfg/choose_interface=auto biosdevname=0 console=tty0 console=ttyS1,115200"
      kernel_options_post: "pci=realloc=off console=tty0 console=ttyS1,115200"
  "Ubuntu-14.04-server-x86_64":
      iso: "http://releases.ubuntu.com/14.04/ubuntu-14.04.3-server-amd64.iso"
      sha256: a3b345908a826e262f4ea1afeb357fd09ec0558cf34e6c9112cead4bb55ccdfb
      kickstart: cephlab_ubuntu.preseed
      kernel_options: "netcfg/choose_interface=auto biosdevname=0 console=tty0 console=ttyS1,115200"
      kernel_options_post: "pci=realloc=off console=tty0 console=ttyS1,115200"
  "Ubuntu-15.04-server-x86_64":
      iso: "http://releases.ubuntu.com/15.04/ubuntu-15.04-server-amd64.iso"
      sha256: 6501c8545374665823384bbb6235f865108f56d8a30bbf69dd18df73c14ccb84
      kickstart: cephlab_ubuntu.preseed
      kernel_options: "netcfg/choose_interface=auto biosdevname=0 console=tty0 console=ttyS1,115200"
      kernel_options_post: "pci=realloc=off console=tty0 console=ttyS1,115200"
