---
- name: Create the sudo group.
  group:
    name: sudo
    state: present
  tags:
    - user

- name: Create the ansible user.
  user:
    name: "{{ ansible_user }}"
    group: sudo
    update_password: on_create
  register: user_created
  tags:
    - user

- name: Delete the ansible users password.
  command: "passwd -d {{ ansible_user }}"
  when: user_created is defined and user_created|changed
  tags:
    - user

- name: Ensure includedir is present in sudoers.
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: visudo -cf %s
  tags:
    - sudoers

- name: Create the cephlab_sudo sudoers.d file.
  template:
    src: cephlab_sudo
    dest: /etc/sudoers.d/cephlab_sudo
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s
  tags:
    - sudoers

- name: Add authorized keys for the ansible user.
  authorized_key: 
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  with_items: ssh_keys
  tags:
    - pubkeys
