---
- name: install nginx web server
  yum:
    name: nginx
    state: present

- name: create nginx docroots
  file:
    path: "/var/www/{{ item }}/htdocs"
    owner: "{{ puddle_user }}"
    mode: 0755
    state: directory
  with_items:
    - "dev-{{ ansible_hostname }}"
    - "{{ ansible_hostname }}"

- name: configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
   - restart nginx

# Note: this file must be installed on the host independent of ansible.
- name: set permissions on htaccess
  file:
    path: '/etc/nginx/htpasswd'
    owner: root
    group: nginx
    mode: 0640
  notify:
   - restart nginx

- name: start the nginx service
  service:
    name: nginx
    state: started
    enabled: yes
