---
- name: Include apt_system vars
  include_vars: apt_systems.yml
  when: ansible_pkg_mgr == "apt"

- name: Include yum_systems vars
  include_vars: yum_systems.yml
  when: ansible_pkg_mgr == "yum"

# Returns 0 if found and 1 if not found
# Task fails if not found.  Hence ignore_errors: true
- name: Check for epel
  shell: "grep -q 'epel' /etc/yum.repos.d/*"
  register: have_epel
  no_log: true
  ignore_errors: true
  when: ansible_pkg_mgr == "yum"

# This task is only run when epel isn't present
- name: Install nrpe without epel
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - http://{{ mirror_host }}/lab-extras/rhel7/x86_64/nagios-common-4.0.8-2.el7.x86_64.rpm
    - http://{{ mirror_host }}/lab-extras/rhel7/x86_64/nrpe-2.15-7.el7.x86_64.rpm
  when: ansible_pkg_mgr == "yum" and
        have_epel.rc == 1

- name: Install nrpe package and dependencies (RHEL/CentOS)
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: epel
  with_items:
    - nrpe
    - smartmontools
  when: ansible_pkg_mgr == "yum" and
        have_epel.rc == 0

- name: Install nrpe package and dependencies (Ubuntu)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nagios-nrpe-server
    - smartmontools
  when: ansible_pkg_mgr == "apt"

- name: Upload nagios sudoers.d for raid utilities.
  template:
    src: nagios/90-nagios
    dest: /etc/sudoers.d/90-nagios
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s

- name: Configure nagios nrpe settings (Ubuntu)
  lineinfile:
    dest: /etc/default/{{ nrpe_service_name }}
    regexp: "^DAEMON_OPTS"
    line: "DAEMON_OPTS=\"--no-ssl\""
  when: ansible_pkg_mgr == "apt"

- name: Configure nagios nrpe settings (RHEL/CentOS)
  lineinfile:
    dest: /etc/sysconfig/{{ nrpe_service_name }}
    regexp: "^NRPE_SSL_OPT"
    line: "NRPE_SSL_OPT=\"-n\""
  when: ansible_pkg_mgr == "yum"

- name: Check firewalld status
  command: systemctl status firewalld
  register: firewalld
  ignore_errors: true
  no_log: true
  when: ansible_pkg_mgr == "yum"

- name: Open nrpe port if firewalld enabled
  firewalld:
    port: 5666/tcp
    state: enabled
    permanent: yes
    immediate: yes
  when: ansible_pkg_mgr == "yum" and (firewalld is defined and firewalld.stdout.find('running') != -1)

- name: Upload nagios nrpe config.
  template:
    src: nagios/nrpe.cfg 
    dest: /etc/nagios/nrpe.cfg
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nagios-nrpe-server

- name: Make sure nagios nrpe service is running.
  service:
    name: "{{ nrpe_service_name }}"
    enabled: yes
    state: started
