---
# vars specific to centos 6.x

yum_repos:
  centos6-fcgi-ceph:
    name: Cent OS 6 Local fastcgi Repo
    baseurl: "http://{{ gitbuilder_host }}/mod_fastcgi-rpm-centos6-x86_64-basic/ref/master/"
    enabled: 1
    gpgcheck: 0
    priority: 2
  centos6-misc-ceph:
    name: Cent OS 6 Local misc Repo
    baseurl: "http://{{ mirror_host }}/misc-rpms/"
    enabled: 1
    gpgcheck: 0
    priority: 2
  rpmforge:
    name: Red Hat Enterprise $releasever - RPMforge.net - dag
    baseurl: "http://{{ mirror_host }}/rpmforge/"
    enabled: 1
    gpgcheck: 0
    protect: 0
  lab-extras:
    name: lab-extras
    baseurl: "http://{{ mirror_host }}/lab-extras/centos6/"
    enabled: 1
    gpgcheck: 0
    priority: 2

packages:
  - '@core'
  - '@base'
  - yum-plugin-priorities
  - yum-plugin-fastestmirror
  - redhat-lsb
  - sysstat
  - gdb
  - git-all
  - python-configobj
  # for running ceph
  - libedit
  - openssl098e
  - boost-thread
  - xfsprogs
  - gdisk
  - parted
  - libgcrypt
  - fuse
  - fuse-libs
  ###
  ###
  ###
  - openssl
  - libuuid
  - btrfs-progs
  # for compiling helpers
  - libatomic_ops-devel
  ###
  # used by workunits
  - attr
  - valgrind
  - python-nose
  - mpich2
  - mpich2-devel
  - ant
  - fsstress
  - iozone
  ###
  # used by the xfstests tasks
  - libtool
  - automake
  - gettext
  - uuid-devel
  - libacl-devel
  - bc
  - xfsdump
  ###
  # for blktrace and seekwatcher
  - blktrace
  - numpy
  - python-matplotlib
  ###
  # for qemu
  - qemu-kvm
  - usbredir
  - genisoimage
  ###
  # for apache and rgw
  - httpd
  - httpd-devel
  - httpd-tools
  - mod_ssl
  - mod_fastcgi-2.4.7-1.ceph.el6
  ###
  - libevent-devel
  - python-devel
  # for pretty-printing xml
  - perl-XML-Twig
  # for java bindings, hadoop, etc.
  - java-1.7.0-openjdk-devel
  - junit4
  # for disk/etc monitoring
  - smartmontools
  # for nfs
  - nfs-utils

epel_packages:
  # for running ceph
  - cryptopp-devel
  - cryptopp
  - fcgi
  # used by workunits
  - dbench
  # used by workunits
  - fuse-sshfs
  - bonnie++
  # for json_xs to investigate JSON by hand
  - perl-JSON
  # for ceph-deploy
  - python-virtualenv
  # for setting BIOS settings
  - smbios-utils
  # for nagios monitoring
  - nrpe
  - nagios-plugins-all
