---
# vars specific to centos 7.x

yum_repos:
  centos7-fcgi-ceph:
    name: CentOS 7 Local fastcgi Repo
    baseurl: "http://{{ gitbuilder_host }}/mod_fastcgi-rpm-centos7-x86_64-basic/ref/master/"
    enabled: 1
    gpgcheck: 0
  lab-extras:
    name: lab-extras
    baseurl: "http://{{ mirror_host }}/lab-extras/centos7/"
    enabled: 1
    gpgcheck: 0

packages:
  - '@core'
  - '@base'
  - yum-plugin-priorities
  - yum-plugin-fastestmirror
  - redhat-lsb
  - sysstat
  - gdb
  - git-all
  - python-configobj
  - gcc-c++
  # for running ceph
  - libedit
  - openssl098e
  - boost-thread
  - xfsprogs
  - gdisk
  - parted
  - libgcrypt
  - fuse
  - fuse-libs
  ###
  # for ceph-deploy
  - python-virtualenv
  ###
  - openssl
  - libuuid
  - btrfs-progs
  # used by workunits
  - attr
  - valgrind
  - python-nose
  - mpich
  - podman
  # for cephadmunit.py's kill,
  - podman-docker
  - ant
  - iozone
  ###
  # used by the xfstests tasks
  - libtool
  - automake
  - gettext
  - libuuid-devel
  - libacl-devel
  - bc
  - xfsdump
  - xfsprogs-devel
  ###
  # for blktrace and seekwatcher
  - blktrace
  - numpy
  - python-matplotlib
  ###
  # for qemu
  - qemu-kvm
  - usbredir
  - genisoimage
  ###
  # for apache and rgw
  - httpd
  - httpd-devel
  - httpd-tools
  - mod_ssl
  - mod_fastcgi-2.4.7-1.ceph.el7.centos
  ### for swift and s3-tests
  - libev-devel
  # for pretty-printing xml
  - perl-XML-Twig
  # for java bindings, hadoop, etc.
  - java-1.6.0-openjdk-devel
  - junit4
  # for nfs
  - nfs-utils
  # for xfstests
  - ncurses-devel
  # for s3 tests
  - python-devel
  - python-virtualenv
  - perl-CPAN
  - python3

epel_packages:
  # for running ceph
  - cryptopp-devel
  - cryptopp
  - fcgi
  # used by workunits
  - dbench
  # used by workunits
  - fuse-sshfs
  - bonnie++
  # for json_xs to investigate JSON by hand
  - perl-JSON-XS
