---
# vars specific to rhel 6.x

common_yum_repos:
  lab-extras:
    name: "lab-extras"
    baseurl: "http://{{ mirror_host }}/lab-extras/rhel6/"
    enabled: 1
    gpgcheck: 0
    priority: 2
  centos6-misc-ceph:
    name: "Cent OS 6 Local misc Repo"
    baseurl: "http://{{ mirror_host }}/misc-rpms/"
    enabled: 1
    gpgcheck: 0
    priority: 2

packages:
  - '@core'
  - '@base'
  - yum-plugin-priorities
  - yum-plugin-fastestmirror
  - redhat-lsb
  - sysstat
  - gdb
  - git-all
  - python-configobj
  # for running ceph
  - libedit
  - openssl098e
  - boost-thread
  - xfsprogs
  - gdisk
  - parted
  - libgcrypt
  - fuse
  - fuse-libs
  ###
  - openssl
  - libuuid
  - btrfs-progs
  # used by workunits
  - attr
  - valgrind
  - python-nose
  - mpich2
  - ant
  - fsstress
  - iozone
  ###
  # used by the xfstests tasks
  - libtool
  - automake
  - gettext
  - libuuid-devel
  - libacl-devel
  - bc
  - xfsdump
  ###
  # for blktrace and seekwatcher
  - blktrace
  - numpy
  - python-matplotlib
  ###
  # for qemu
  - qemu-kvm
  - usbredir
  - genisoimage
  ###
  # for apache and rgw
  - httpd
  - httpd-devel
  - httpd-tools
  - mod_ssl
  ###
  - libevent-devel
  # for pretty-printing xml
  - perl-XML-Twig
  # for java bindings, hadoop, etc.
  - java-1.6.0-openjdk-devel
  - junit4
  # for disk/etc monitoring
  - smartmontools
  # for nfs
  - nfs-utils


epel_packages:
  # for running ceph
  - gperftools-devel
  - cryptopp-devel
  - cryptopp
  - fcgi
  # used by workunits
  - dbench
  - fuse-sshfs
  - bonnie++
  # for json_xs to investigate JSON by hand
  - perl-JSON-XS
  # for ceph-deploy
  - python-virtualenv
  # for setting BIOS settings
  - smbios-utils

nfs_service: nfs
