---
apt_repos:
  # mod_fastcgi for radosgw
  - "deb http://gitbuilder.ceph.com/libapache-mod-fastcgi-deb-trusty-x86_64-basic/ref/master/ trusty main"

packages:
  - libboost-thread1.54.0
  - mpich
  - qemu-system-x86
#  - blkin
  - lttng-tools
  ###
  # for setting BIOS settings
  ###
  - libcrypto++9
  ###
  # used by workunits
  - mpich2
  - libmpich2-dev
  - python-dev

non_aarch64_packages:
  - libgoogle-perftools4
  - iozone3
  - dmapi
  - libssl0.9.8
