---
apt_repos: []

packages:
  - libgoogle-perftools4
# FIXME: not available on vivid, figure out what's available and use it
# - libboost-thread1.54.0
  - mpich
  - qemu-system-x86
# FIXME: not available on vivid, figure out what's available and use it
#  - blkin
  - lttng-tools
  ###
  # for setting BIOS settings
  ###
  - libcrypto++9
  ###
  # used by workunits
  - mpich2
  - libmpich2-dev

non_aarch64_packages:
  - iozone3
  - dmapi
  - libssl0.9.8
