---
- name: Ensure packages are not present.
  apt:
    name: "{{ item }}"
    state: absent
  with_items: ceph_packages_to_remove|list + packages_to_remove|list
  when: ceph_packages_to_remove|length > 0 or
        packages_to_remove|length > 0

- name: Upgrade packages
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items: packages_to_upgrade
  when: packages_to_upgrade|length > 0

- name: Upgrade non aarch64 packages
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items: non_aarch64_packages_to_upgrade
  when:
    non_aarch64_packages_to_upgrade|length > 0 and
    ansible_architecture != "aarch64"

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present 
  with_items: packages|list + common_packages|list
  when: packages|length > 0 or
        common_packages|length > 0

- name: Install non aarch64 packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: non_aarch64_packages|list + non_aarch64_common_packages|list
  when: ansible_architecture != "aarch64"
