---
- name: Ensure packages are not present.
  apt:
    name: "{{ ceph_packages_to_remove|list + packages_to_remove|list }}"
    state: absent
    force: yes
  when: ceph_packages_to_remove|length > 0 or
        packages_to_remove|length > 0

- name: Upgrade packages
  apt:
    name: "{{ packages_to_upgrade|list }}"
    state: latest
    force: yes
  when: packages_to_upgrade|length > 0

- name: Upgrade non aarch64 packages
  apt:
    name: "{{ non_aarch64_packages_to_upgrade|list }}"
    state: latest
    force: yes
  when:
    non_aarch64_packages_to_upgrade|length > 0 and
    ansible_architecture != "aarch64"

- name: Install packages
  apt:
    name: "{{ packages|list + common_packages|list }}"
    state: present 
    force: yes
  when: packages|length > 0 or
        common_packages|length > 0

- name: Install non aarch64 packages
  apt:
    name: "{{ non_aarch64_packages|list + non_aarch64_common_packages|list }}"
    state: present
    force: yes
  when: ansible_architecture != "aarch64"
